---
output: 
  html_document:
    fig_height: 10
    fig_width: 10
---

# Preliminaries

Loading libraries

```{r libraries}
library(ggplot2)
library(dplyr)
library(ggpubr)
```

Loading databases

```{r databases}
setwd('..')
path <- getwd()
setwd(paste(path, "/Results/MergedData", sep = ""))
#Read data
load("MergedDat.RData")
```

# Data cleaning

I'll remove participants without Male or Female self-identified sex

```{r data cleaning}
MergedDat[[1]]$IID[!(MergedDat[[1]]$Sex == "Male" | MergedDat[[1]]$Sex == "Female")]
cleanSex       <- MergedDat[[1]]$Sex == "Male" | MergedDat[[1]]$Sex == "Female"
MergedDat[[1]] <- dplyr::filter(MergedDat[[1]], cleanSex)
MergedDat[[2]] <- dplyr::filter(MergedDat[[2]], cleanSex)
MergedDat[[3]] <- dplyr::filter(MergedDat[[3]], cleanSex)
MergedDat[[1]]$Sex <- droplevels(MergedDat[[1]]$Sex)
```


# Descriptive and exploratory analyses

```{r summary}
summary(MergedDat[[1]])
```

Scatter plot in Face PCA, with ancestry populations

```{r}
plotpops <- function(dat, x1, y1, continent)
{
  p1 <- ggplot(dat, aes_string(x = x1, y = y1, color = continent)) +
            geom_point(alpha = 0.3, size = 2) + theme_pubr() +
            scale_color_discrete(name = "Continent")
  p1 <- ggpar(p1, palette = "jama")
  return(p1)
}

p1 <- plotpops(MergedDat[[2]], "PC1", "PC2", MergedDat[[1]]$continent)
p2 <- plotpops(MergedDat[[2]], "PC3", "PC4", MergedDat[[1]]$continent)
p3 <- plotpops(MergedDat[[2]], "PC5", "PC6", MergedDat[[1]]$continent)
p4 <- plotpops(MergedDat[[2]], "PC7", "PC8", MergedDat[[1]]$continent)
ggarrange(p1, p2, p3, p4, nrow = 2, ncol = 2,
          common.legend = TRUE, legend = "right", 
          align = "v")
```

```{r}
source("PlotPCs.R")
p1 = PlotPCs(MergedDat[[2]], MergedDat[[1]]$continent, "PC1", "PC9")
p2 = PlotPCs(MergedDat[[2]], MergedDat[[1]]$continent, "PC10", "PC19")
p3 = PlotPCs(MergedDat[[2]], MergedDat[[1]]$continent, "PC20", "PC29")
p4 = PlotPCs(MergedDat[[2]], MergedDat[[1]]$continent, "PC30", "PC39")
ggarrange(p1, p2, p3, p4,
          common.legend = TRUE, legend = "right", 
          align = "v")
```

```{r means plots}
meanspop <- MergedDat[[2]] %>% group_by(MergedDat[[1]]$continent) %>% 
                summarise_all(funs(mean))
colnames(meanspop)[1] <- "continent"

plotmeans <- function(dat1, dat2, x1, y1, continent)
{
  p1 <- ggplot(data = dat2, aes_string(x = x1, y = y1, color = continent)) + 
          geom_point(alpha = 0.3) + 
          geom_label(data = dat1, aes_string(x = x1, y = y1, label="continent", fill = "continent"), 
                     colour = "white", fontface = "bold", alpha = 0.7) +
          theme_pubr(legend = "none")
  p1 <- ggpar(p1, palette = "jama")
  return(p1)
}

p1 <- plotmeans(meanspop, MergedDat[[2]],"PC1", "PC2", MergedDat[[1]]$continent)
p2 <- plotmeans(meanspop, MergedDat[[2]],"PC3", "PC4", MergedDat[[1]]$continent)
p3 <- plotmeans(meanspop, MergedDat[[2]],"PC5", "PC6", MergedDat[[1]]$continent)
p4 <- plotmeans(meanspop, MergedDat[[2]],"PC7", "PC8", MergedDat[[1]]$continent)
p5 <- plotmeans(meanspop, MergedDat[[2]],"PC9", "PC10", MergedDat[[1]]$continent)
p6 <- plotmeans(meanspop, MergedDat[[2]],"PC11", "PC12", MergedDat[[1]]$continent)

ggarrange(p1, p2, p3, p4, p5, p6,
          nrow = 3, ncol = 2, 
          align = "v")
```

```{r plot ellipses}
plotellip <- function(dat1, x1, y1, continent)
{
  p1 <- ggplot(dat1, aes_string(x = x1, y = y1, color = continent)) + 
          geom_point(alpha = 0.3) + 
          stat_ellipse() +
          theme_pubr(legend = "none")
  p1 <- ggpar(p1, palette = "jama")
  return(p1)
}

p1 <- plotellip(MergedDat[[2]], "PC1", "PC2", MergedDat[[1]]$continent)
p2 <- plotellip(MergedDat[[2]], "PC3", "PC4", MergedDat[[1]]$continent)
p3 <- plotellip(MergedDat[[2]], "PC5", "PC6", MergedDat[[1]]$continent)
p4 <- plotellip(MergedDat[[2]], "PC7", "PC8", MergedDat[[1]]$continent)
p5 <- plotellip(MergedDat[[2]], "PC9", "PC10", MergedDat[[1]]$continent)
p6 <- plotellip(MergedDat[[2]], "PC11", "PC12", MergedDat[[1]]$continent)

ggarrange(p1, p2, p3, p4, p5, p6,
          nrow = 3, ncol = 2, 
          align = "v")


```


```{r eval=F}
noeur <- !(MergedDat[[1]]$groups == "2")

Males1   <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "1" &  MergedDat[[1]]$Sex == "Male") )
Females1 <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "1" &  MergedDat[[1]]$Sex == "Female") )
Males2   <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "2" &  MergedDat[[1]]$Sex == "Male") )
Females2 <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "2" &  MergedDat[[1]]$Sex == "Female") )
Males3   <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "3" &  MergedDat[[1]]$Sex == "Male") )
Females3 <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "3" &  MergedDat[[1]]$Sex == "Female") )
Males4   <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "4" &  MergedDat[[1]]$Sex == "Male") )
Females4 <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "4" &  MergedDat[[1]]$Sex == "Female") )
Males5   <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "5" &  MergedDat[[1]]$Sex == "Male") )
Females5 <- colMeans(filter(MergedDat[[2]], MergedDat[[1]]$groups == "5" &  MergedDat[[1]]$Sex == "Female") )

consensus <- as.data.frame(t(data.frame(Males1, Females1, Males2, Females2, Males3, Females3, Males4, Females4, Males5, Females5)))
remove(Males1, Females1, Males2, Females2, Males3, Females3, Males4, Females4, Males5, Females5)

p1 <- ggplot(filter(MergedDat[[2]], noeur), aes(PC1, PC2, colour=filter(MergedDat[[1]], noeur)$groups )) + 
  geom_point(alpha=0.1) + 
  geom_point(data = consensus[1:2,], aes(PC1, PC2), color="red", size=3) + 
  geom_point(data = consensus[3:4,], aes(PC1, PC2), color="blue", size=3) +
  geom_point(data = consensus[5:6,], aes(PC1, PC2), color="green", size=3) +
  geom_point(data = consensus[7:8,], aes(PC1, PC2), color="yellow", size=3) + 
  geom_point(data = consensus[9:10,], aes(PC1, PC2), color="pink", size=3) +
  theme(legend.position="none") 

p2 <- ggplot(filter(MergedDat[[2]], noeur), aes(PC3, PC4, colour=filter(MergedDat[[1]], noeur)$groups)) + 
  geom_point(alpha=0.1) + 
    geom_point(data = consensus[1:2,], aes(PC3, PC4), color="red", size=3) + 
  geom_point(data = consensus[3:4,], aes(PC3, PC4), color="blue", size=3) +
  geom_point(data = consensus[5:6,], aes(PC3, PC4), color="green", size=3) +
  geom_point(data = consensus[7:8,], aes(PC3, PC4), color="yellow", size=3) + 
  geom_point(data = consensus[9:10,], aes(PC3, PC4), color="pink", size=3) +
  theme(legend.position="none") 
          
p3 <- ggplot(filter(MergedDat[[2]], noeur), aes(PC5, PC6, colour=filter(MergedDat[[1]], noeur)$groups)) + 
  geom_point(alpha=0.1) + 
  geom_point(data = consensus[1:2,], aes(PC5, PC6), color="red", size=3) + 
  geom_point(data = consensus[3:4,], aes(PC5, PC6), color="blue", size=3) +
  geom_point(data = consensus[5:6,], aes(PC5, PC6), color="green", size=3) +
  geom_point(data = consensus[7:8,], aes(PC5, PC6), color="yellow", size=3) + 
  geom_point(data = consensus[9:10,], aes(PC5, PC6), color="pink", size=3) +
  theme(legend.position="none")
             
p4 <- ggplot(filter(MergedDat[[2]], noeur), aes(PC7, PC8, colour=filter(MergedDat[[1]], noeur)$groups)) + 
  geom_point(alpha=0.1) + 
  geom_point(data = consensus[1:2,], aes(PC7, PC8), color="red", size=3) + 
  geom_point(data = consensus[3:4,], aes(PC7, PC8), color="blue", size=3) +
  geom_point(data = consensus[5:6,], aes(PC7, PC8), color="green", size=3) +
  geom_point(data = consensus[7:8,], aes(PC7, PC8), color="yellow", size=3) + 
  geom_point(data = consensus[9:10,], aes(PC7, PC8), color="pink", size=3) +
  theme(legend.position="none")
             
#grid.arrange(p1, p2, p3, p4, ncol=2)
```

