---
title: Main Results
output:
  html_document: default
---

Libraries

```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggpubr)
library(broom)
library(car)
source("PhenotypicChangeTests.R")
```

Databases

```{r databases, warning=FALSE, message=FALSE}
setwd('..')
path <- getwd()
setwd(paste(path, "/Results/MergedData", sep = ""))
load("MergedDat.RData")
```

Getting vectors for total, allometric, and non-allometric components

```{r}
####REGRESSION MODELS AND VECTOR####
matrix  <- dplyr::select(MergedDat, starts_with("FacePC"))
covs    <- MergedDat %>% dplyr::select(c("Age", "Height", "BMI","Sex", "k3", "k4", "k5", "k6", "k7", "k8", "k9", "k10"))
matrix_covs <- na.omit(cbind(matrix, covs))
matrix_covs[,c(68:70)] <- scale(matrix_covs[,c(68:70)]) #Scaling data

sex_vectors_all <- NULL
for (i in 3:10){
  ks <- paste("k", i, sep="") # Creating k string
  print(ks)
  model_mat <- model.matrix( ~ Age + Height + BMI + Sex * get(ks), data=matrix_covs) #Creating design matrix
  y_mat     <- matrix_covs[,1:67] # Y matrix
  covs_mat       <- model_mat[,1:4] # Covariate matrix
  covs_mat_total <- model_mat[,c(1,2,4)] # Covariate without height
  x_mat_full <- model_mat[,5: (3+(i*2)) ] # Full model
  x_mat_red  <- model_mat[,5:(4+i)] # Reduced model
  #Vector change tests
  out_mat       <- run_vector_change(y_mat, covs_mat, x_mat_red, x_mat_full) # Vector change test for non-allometric
  out_mat_total <- run_vector_change(y_mat, covs_mat_total, x_mat_red, x_mat_full) # Vector change test for total
  assign(paste("out_mat_", ks, sep = ""), out_mat)
  assign(paste("out_mat_total_", ks, sep = ""), out_mat_total)
  #Angle and diff p-value tables
  angle_table <- pairwise_pvals(out_mat)
  diff_table  <- pairwise_pvals(out_mat, 0)
  angle_table_total <- pairwise_pvals(out_mat_total)
  diff_table_total  <- pairwise_pvals(out_mat_total, 0)
  assign(paste("angle_pvals_", ks, sep = ""), angle_table)
  assign(paste("diff_pvals_", ks, sep = ""), diff_table)
  assign(paste("angle_pvals_total_", ks, sep = ""), angle_table_total)
  assign(paste("diff_pvals_total_", ks, sep = ""), diff_table_total)
  #Sex vectors
  sex_vectors <- get_sex_vectors(y_mat, covs_mat, x_mat_full)
  sex_vectors_all <- rbind(sex_vectors_all, sex_vectors)
}
```

Adjusting p-values

```{r pvalues}
pvals_list <- mget(ls(pattern = "pvals_k"))
pvals      <- unlist(lapply(pvals_list, function(x) x[lower.tri(x)]))
adjusted_pvals <- p.adjust(pvals, method = "BH")

pvals_adjusted_list <- pvals_list
start = 1
end   = 0
for (i in 1:length(pvals_adjusted_list)){
  n_vals <- length(pvals_adjusted_list[[i]][lower.tri(pvals_adjusted_list[[i]])])
  end = end + n_vals
  pvals_adjusted_list[[i]][lower.tri(pvals_adjusted_list[[i]]) ] <- adjusted_pvals[start:end]
  start = start + n_vals
}

pvals_total_list <- mget(ls(pattern = "pvals_total_k"))
pvals            <- unlist(lapply(pvals_total_list, function(x) x[lower.tri(x)]))
adjusted_pvals   <- p.adjust(pvals, method = "BH")
pvals_adjusted_total_list <- pvals_total_list
start = 1
end   = 0
for (i in 1:length(pvals_adjusted_total_list)){
  n_vals <- length(pvals_adjusted_total_list[[i]][lower.tri(pvals_adjusted_total_list[[i]])])
  end = end + n_vals
  pvals_adjusted_total_list[[i]][lower.tri(pvals_adjusted_total_list[[i]]) ] <- adjusted_pvals[start:end]
  start = start + n_vals
}
```

Saving databases

```{r save}
setwd(paste(path, "/Results/Vectors", sep = ""))
write.csv(sex_vectors_all, "sex_vectors.csv", row.names = F)
save(pvals_adjusted_list, pvals_adjusted_total_list, file = "Pvals.RData")
```

