#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l walltime=48:00:00
#PBS -l pmem=8gb
#PBS -A jlt22_b_g_sc_default
#PBS -j oe

#Move to work folder
cd ~/work/phasing

#Download things
#Beagle
if [ ! -f beagle.24May18.276.jar ]; then
  echo
  echo "Downloading beagle.24May18.276.jar"
  wget http://faculty.washington.edu/browning/beagle/beagle.24May18.276.jar
fi

#Genetic map
if [ ! -f plink.GRCh37.map.zip ]; then
  echo
  echo "Downloading plink.GRCh37.map.zip"
  wget http://bochet.gcc.biostat.washington.edu/beagle/genetic_maps/plink.GRCh37.map.zip
fi
#Unzip it
unzip plink.GRCh37.map.zip

#1000G reference samples
for i in {1..22}
do
	wget http://bochet.gcc.biostat.washington.edu/beagle/1000_Genomes_phase3_v5a/b37.bref3/chr${i}.1kg.phase3.v5a.b37.bref
done

#Need to have 1000G reference sample, HapMap 3 hg19 genetic map, target sample, beagle 5 files
#For each chromosome run the script
for i in {1..22}
do
	java -jar beagle.24May18.276.jar gt=Cleaned_split_${i}.recode.vcf ref=chr${i}.1kg.phase3.v5a.b37.bref map=plink.chr${i}.GRCh37.map out=Cleaned_phased impute=false 
done
