#!/bin/bash
#PBS -l nodes=1:ppn=4
#PBS -l walltime=24:00:00
#PBS -l pmem=8gb
#PBS -A jlt22_b_g_sc_default
#PBS -j oe

#Move to work folder
cd ~/work/phasing

#Need to have 1000G reference sample, HapMap 3 hg19 genetic map, target sample, beagle 5 files
#For each chromosome run the script
for i in {1..22}
do
	java -jar beagle.24May18.276.jar gt=Cleaned_split_${i}.recode.vcf ref=chr${i}.1kg.phase3.v5a.b37.bref map=plink.chr${i}.GRCh37.map out=Cleaned_phased impute=false 
done
